services:
  database:
    container_name: database
    image: postgres:16.3-alpine
    restart: always
    env_file:
      - .env.production
    volumes:
      - data:/var/lib/postgresql/data
  next-app:
    container_name: next-app
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - next-app
    ports:
      - 80:80
volumes:
  data:
