services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/configdb
    ports:
      - "27017:27017"
    expose:
      - 27017

  server:
    build:
      context: ./server
    restart: always
    environment:
      - PORT=8000
      - DB_CONNECT_STRING=mongodb://mongodb:27017
      - CLIENT_URL=http://localhost
      - JWT_KEY=お前はもう死んでいる
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      args:
        - SERVER_URL=/
        - FIREBASE_STORAGE=robotics-hcmus-storage.appspot.com
    restart: always
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - server

volumes:
  mongo-data:
